trigger: none

pr: none

pool:
  vmImage: macos-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: | 
    chmod +x gradlew
  
- script: |
    fastlane deploy_room
  displayName: 'Uploading Room to Artifactory'
  env:
    ARTIFACTORY_PASSWORD: $(artifactory_password)