# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Upload Room artifacts to Artifactory"
  lane :deploy_room do
    Dir.chdir("..") do
      artifactsRootPath = "out/room-playground/room-playground/build/support_repo"
      sh "rm -rfv #{artifactsRootPath}/androidx/room/*"
      sh "./room/gradlew -p ./room createArchive"
      artifacts = Dir["#{artifactsRootPath}/androidx/room/*/*/*.{jar,aar,pom}"]
      artifacts.each do |artifact|
        dirname = File.basename(Dir.getwd)
        repoPath = artifact.partition(artifactsRootPath).last
        filePath = "#{dirname}/#{artifact}"
        artifactory(
          username: ENV["ARTIFACTORY_USER"],
          password: ENV["ARTIFACTORY_PASSWORD"],
          endpoint: ENV["ARTIFACTORY_URL"],
          file: filePath,   # File to upload
          repo: "gradle-release-local",   # Artifactory repo
          repo_path: repoPath   # Path to place the artifact including its filename
        )
      end
    end
  end

end